// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using controleDePontoV1.Context;

namespace controleDePontoV1.Migrations
{
    [DbContext(typeof(PontoDBContext))]
    partial class PontoDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("controleDePontoV1.Models.Colaborador", b =>
                {
                    b.Property<int>("codigo")
                        .HasColumnType("int")
                        .HasColumnName("codigo");

                    b.Property<int>("active")
                        .HasColumnType("int");

                    b.Property<int>("equipe")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("papel")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sobreNome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo");

                    b.ToTable("colaboradores");
                });

            modelBuilder.Entity("controleDePontoV1.Models.ControleApontamento", b =>
                {
                    b.Property<int>("codigo_Colaborador")
                        .HasColumnType("int")
                        .HasColumnName("codigo_Colaborador");

                    b.Property<int>("codigo_Equipe")
                        .HasColumnType("int")
                        .HasColumnName("codigo_Equipe");

                    b.Property<int>("codigo_Projeto")
                        .HasColumnType("int")
                        .HasColumnName("codigo_Projeto");

                    b.Property<DateTime>("dia_Marcao")
                        .HasColumnType("dateTime")
                        .HasColumnName("dateTime");

                    b.Property<DateTime>("dia_Fim")
                        .HasColumnType("datetime2");

                    b.HasKey("codigo_Colaborador", "codigo_Equipe", "codigo_Projeto", "dia_Marcao");

                    b.ToTable("controleApontamento");
                });

            modelBuilder.Entity("controleDePontoV1.Models.Equipe", b =>
                {
                    b.Property<int>("codigo")
                        .HasColumnType("int")
                        .HasColumnName("codigo");

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo");

                    b.ToTable("equipes");
                });

            modelBuilder.Entity("controleDePontoV1.Models.HistoricoEquipe", b =>
                {
                    b.Property<int>("codigo_Colaborador")
                        .HasColumnType("int")
                        .HasColumnName("codigo_Colaborador");

                    b.Property<int>("codigo_Equipe")
                        .HasColumnType("int")
                        .HasColumnName("codigo_Equipe");

                    b.Property<DateTime>("dataDaAlteracao")
                        .HasColumnType("dateTime")
                        .HasColumnName("dataDaAlteracao");

                    b.HasKey("codigo_Colaborador", "codigo_Equipe");

                    b.ToTable("histEquipes");
                });

            modelBuilder.Entity("controleDePontoV1.Models.Papel", b =>
                {
                    b.Property<int>("codigo")
                        .HasColumnType("int")
                        .HasColumnName("codigo");

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo");

                    b.ToTable("papeis");
                });

            modelBuilder.Entity("controleDePontoV1.Models.Projeto", b =>
                {
                    b.Property<int>("codigo")
                        .HasColumnType("int")
                        .HasColumnName("codigo");

                    b.Property<string>("descrição")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo");

                    b.ToTable("projetos");
                });
#pragma warning restore 612, 618
        }
    }
}
